on:
  push:
    branches:
      - main
      - master
    paths:
      - '.github/workflows/validate-ctv.yml'
      - 'MissingData.md'
  pull_request:
    branches:
      - main
      - master
  paths:
      - '.github/workflows/validate-ctv.yml'
      - 'MissingData.md'

name: Validate task view

jobs:
  validate-ctv:
    runs-on: ubuntu-latest
    steps:
      - uses: tuxette/actions@main
