on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: Validate task view

jobs:
  validate-ctv:
    runs-on: ubuntu-latest
    steps:
      - uses: tuxette/actions@main
